apiVersion: batch/v1
kind: Job
metadata:
  name: job-data-download-sso
spec:
  template:
    spec:
      automountServiceAccountToken: false
      containers:
      - name: pod-data-download-sso # Replace the sso with your pawprint name
        image: ubuntu:20.04
        command: ["/bin/sh","-c"]
        args:
        - cp -r /sso/* /data/       # Replace the sso with your pawprint name
        volumeMounts:
        - mountPath: /sso           # Replace the sso with your pawprint name
          name: source
        - mountPath: /data
          name: destination 
        resources:
            limits:
              memory: 10Gi
              cpu: "4"
            requests:
              memory: 10Gi
              cpu: "4"     
      volumes:
      - name: source
        persistentVolumeClaim:
          claimName: cloudcomp-data
      - name: destination
        persistentVolumeClaim:
          claimName: cloudcomp-sso  # Replace the sso with your pawprint name
      restartPolicy: Never      
  backoffLimit: 0
