apiVersion: batch/v1
kind: Job
metadata:
  name: job-copy-data-sso
spec:
  template:
    spec:
      automountServiceAccountToken: false
      containers:
      - name: pod-copy-data-sso   # Replace the sso with your pawprint name
        image: ubuntu:20.04
        command: ["/bin/sh","-c"]
        args:
        - cp -r /data/* /newdata/
        volumeMounts:
        - mountPath: /data          # source: your existing PVC (with image1.npy, image2.npy)
          name: source
        - mountPath: /newdata       # destination: your new, second PVC
          name: destination
        resources:
            limits:
              memory: 10Gi
              cpu: "4"
            requests:
              memory: 10Gi
              cpu: "4"
      volumes:
      - name: source
        persistentVolumeClaim:
          claimName: sso-pv        # Replace with your first PVC name (e.g. <your_sso>-pv)
      - name: destination
        persistentVolumeClaim:
          claimName: sso-pv-new    # Replace with your second PVC name (e.g. <your_sso>-pv-new), created before running this job
      restartPolicy: Never
  backoffLimit: 0
