apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: your_sso-pv-new     # Replace this with your SSO
spec:
  storageClassName: rook-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
